# config.yaml
api:
  baseUrl: https://jsonplaceholder.typicode.com
  version: v1
  auth:
    type: Bearer
endpoints:
  delete-post:
    method: DELETE
    path: /posts/{id}
    parameters:
      id:
        type: int
        description: The ID of the post to delete.
        in: path
        required: true
    defaults:
      id: 1
  create-user:
    method: POST
    path: /users
    parameters:
      name:
        type: string
        description: The name of the user.
        required: true
      email:
        type: string
        description: The email of the user.
        required: true
        mode: env
    defaults:
      name: "John Doe"
      email: MY_EMAIL
  create-post:
    method: POST
    path: /posts
    parameters:
      title:
        type: string
        description: The title of the post.
        required: true
      body:
        type: string
        description: The body of the post.
        required: true
      userId:
        type: int
        description: The ID of the user creating the post.
    defaults:
      title: "My First Post"
      body: "This is the body of my first post."
      userId: 1
  update-post:
    method: PUT
    path: /posts/{id}
    parameters:
      id:
        type: int
        description: The ID of the post to update.
        in: path
        required: true
      title:
        type: string
        description: The title of the post.
        required: true
      body:
        type: string
        description: The body of the post.
        required: true
      userId:
        type: int
        description: The ID of the user updating the post.
    defaults:
      id: 102
      title: "My Updated Post"
      body: "This is the updated body of my post."
      userId: 1