# config.yaml
api:
  baseUrl: https://jsonplaceholder.typicode.com
  version: v1
  auth:
    type: Bearer
endpoints:
  delete-post:
    method: DELETE
    path: /posts/{id}
    parameters:
      id:
        type: int
        description: The ID of the post to delete.
        in: path
        required: true
    defaults:
      id: 1
  create-post:
    method: POST
    path: /posts
    parameters:
      title:
        type: string
        description: The title of the post.
        required: true
        validation:
          minLength: 3
          maxLength: 100
      body:
        type: string
        description: The body of the post.
        required: true
        validation:
          minLength: 10
          maxLength: 500
      userId:
        type: int
        description: The ID of the user creating the post.
    defaults:
      title: "My First Post"
      body: "This is the body of my first post."
    
  # get-pokemons:
  #   method: GET
  #   path: /pokemon
  # get-pokemon:
  #   method: GET
  #   path: /pokemon/{slug}
  #   parameters:
  #     slug:
  #       type: string
  #       description: The slug of the pokemon
  #       in: path
  #   defaults:
  #     slug: pikachu


  # create-user:
  #   method: POST
  #   mode: default
  #   path: /users 
  #   parameters:
  #     name:
  #       type: string
  #       mode: seed
  #       description: The name of the user.
  #       validation:
  #         minLength: 3
  #         maxLength: 50
  #     email:
  #       type: string
  #       mode: env
  #       description: The email of the user.
  #   defaults:
  #     name: "John Doe"
  #     email: MY_EMAIL

  # list-users:
  #   method: GET
  #   path: /users
  #   parameters:
  #     limit:
  #       type: int
  #       description: The maximum number of users to return.
  #       in: query
  #       required: false
  #     offset:
  #       type: int
  #       description: The number of users to skip.
  #       in: query
  #       required: false

  # get-user-by-id:
  #   method: GET
  #   path: /users/{id}
  #   parameters:
  #     id:
  #       type: int
  #       description: The ID of the user.
  #       in: path
  #       required: true
  #   defaults:
  #     id: 1