api:
  baseUrl: http://localhost:8080
  headers:
    Authorization: Bearer {{token}}
    ContentType: application/json
endpoints:
  login:
    method: POST
    path: /login
    parameters:
      email:
        type: string
        required: true
      password:
        type: string
        required: true
    set-variables:
      body:
        token: token
    defaults:
      email: user@example.com
      password: password
  test:
    method: GET
    path: /
  protected:
    method: GET
    path: /protected
